### ISSUE TITLE
Don't strech out details as much.

### ISSUE THREAD

**Issue by trypsynth** [Mohamed00/AltIBMTTSDictionaries#1]
I'm not honestly sure I like how this dictionary handles the word "details." It makes it sound like there's two E's when there's not. Could this be fixed?

**Comment by Mohamed00** [comment]
Hi, not sure if I can fix that without making it sound odd. I can remove 
the secondary stress from the tail part, but that would break the t 
sound. To be honest I've been considering removing that for a while, as 
the original pronunciation is a bit out there, but does appear as a 
valid pronunciation in several sources, but I've been really reluctant 
to do it.

**Comment by trypsynth** [comment]
Yeah, not sure honestly. This way certainly works, just wasn't sure if you could do much about it. The dict entry does sound too stressed, at least to me.

**Comment by Mohamed00** [comment]
Unfortunately I can't really do much about that.

**Comment by trypsynth** [comment]
I'd vote to just remove it. Up to you, it's your dict, but that's what I'd do

**Comment by Mohamed00** [comment]
I just removed it actually. I had been considering doing that for quite a while, but 
you filing this issue was the push I needed to finally do it.

**Comment by trypsynth** [comment]
Alright, thanks! :)
