### ISSUE TITLE
How to handle words that have two proper sayings, neither of which are how Eloquence says it?

### ISSUE THREAD

**Issue by trypsynth** [Mohamed00/AltIBMTTSDictionaries#46]
I'm presently trying to work on correcting the word carabiner. I found at least 3 sources that say it how I do, and put it in my working copy of the dictionary:
https://www.youtube.com/watch?v=Ql1VQP1zgg8
https://www.youtube.com/watch?v=6Ft6KPLPp4c
and https://www.youtube.com/watch?v=HWRPzCamSMs
However, I found another that says it slightly differently:
https://www.youtube.com/watch?v=_RxfgygfNYM
That's not how Eloquence says it, but it is another way. How should I proceed here? Go with the one that seems more common?

**Comment by Mohamed00** [comment]
Ultimately I don't really care as long as the pronunciation is valid. In 
this case I tend to see `[kerxb1inR] in the sources I normally check.

**Comment by trypsynth** [comment]
Okay, sounds good. My way of doing it was slightly different. They sound exactly the same to me, but I'll PR yours :)
